spring:
  application:
    name: sistema-de-ponto
  
  # Habilitação das Virtual Threads (Project Loom) do Java 21 para escalabilidade
  threads:
    virtual:
      enabled: true

  # Configuração de Conectividade com H2 em memória para testes locais
  datasource:
    url: jdbc:h2:mem:sistema_ponto;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Configurações do JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
